[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-DFS-2016",
]
copyleft = "deny"

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
