[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
    # difference is unmaintained
    "RUSTSEC-2020-0095",
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
]
copyleft = "deny"

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
