[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-DFS-2016",
]
copyleft = "deny"

[bans]
multiple-versions = "deny"
skip = [
    # Doesn't matter
    { name = "hermit-abi" },
]
skip-tree = [
    # dev only but still sigh
    { name = "windows-sys", version = "<0.48.0" },
    # petgraph uses an older indexmap
    { name = "indexmap", version = "=1.9.3" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
